name: Build and upload

on:
  push:
    branches:
      - main

env:
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: 17

      - run: wget https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default -O butler.zip
      - run: unzip butler.zip

      - run: chmod +x butler && chmod +x gradlew

      - run: ./gradlew lwjgl3:jar html:dist lwjgl3:packageWinX64 lwjgl3:packageLinuxX64

      - run: mv lwjgl3/build/lib/*.jar A-Rather-Festive-Birb.jar

      - run: ./butler push html/build/dist lyze237/a-rather-festive-birb:html
      - run: ./butler push A-Rather-Festive-Birb.jar lyze237/a-rather-festive-birb:jar
      - run: ./butler push lwjgl3/build/construo/winX64 lyze237/a-rather-festive-birb:win
      - run: ./butler push lwjgl3/build/construo/linuxX64 lyze237/a-rather-festive-birb:linux
